recipebook/ledger/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RecipeListView, RecipeDetailView

urlpatterns = [
    path('recipes/list/', RecipeListView.as_view(), name='recipes_list'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='recipe_detail'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

app_name = "ledger"

recipebook/recipebook/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('ledger.urls', namespace="ledger")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

recipebook/ledger/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    bio = models.TextField(blank=True)


class Ingredient(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'ingredient_detail',
            kwargs={'pk': self.pk}
        )


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'recipe_detail',
            kwargs={'pk': self.pk}
        )


class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=100)
    ingredient = models.ForeignKey(
        Ingredient,
        on_delete=models.CASCADE,
        related_name="recipe"
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="ingredients"
    )

    def __str__(self):
        return f"{self.quantity} of {self.ingredient.name}"

recipebook/ledger/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from .models import Recipe


class RecipeListView(ListView):
    model = Recipe
    template_name = 'ledger/recipes_list.html'
    context_object_name = 'recipes'


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'ledger/recipe_detail.html'
    context_object_name = 'recipe'

recipebook/ledger/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Recipe Book{% endblock %}</title>
</head>
<body>
    <h1>Recipe Book</h1>
    {% block login_logout %}
    {% endblock %}
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

recipebook/ledger/templates/ledger/recipe_detail.html
{% extends 'base.html' %}

{% block title %}{{object.name}}{% endblock %}
{% block content %}
    <h2>{{ recipe.name }}</h2>
    <p>Author: {{ recipe.author.profile.name }}</p>
    <ul>
        {% for recipe_ingredient in recipe.ingredients.all %}
            <li>{{ recipe_ingredient.ingredient.name }} ({{ recipe_ingredient.quantity }})</li>
        {% endfor %}
    </ul>
    <a href="{% url 'ledger:recipes_list' %}">Back to Recipe List</a>
    <br><br>
    <form method="POST" action="{% url 'logout' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

recipebook/ledger/templates/ledger/recipes_list.html
{% extends 'base.html' %}

{% block title %}Recipes List{% endblock %}

{% block content %}
  <h2>Recipe List</h2>
  <ul>
    {% for recipe in object_list %}
    <li>
      <a href="{% url 'ledger:recipe_detail' pk=recipe.pk %}">
        {{ recipe.name }}
      </a>
    </li>
    {% endfor %}
  </ul>
{% endblock %}